steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - VITE_GOOGLE_MAPS_API_KEY
      - -t
      - ${_IMAGE}
      - .
    secretEnv:
      - VITE_GOOGLE_MAPS_API_KEY
substitutions:
  _IMAGE: europe-west1-docker.pkg.dev/walking-off-sunshine/walking-off-sunshine/frontend:latest
availableSecrets:
  secretManager:
    - versionName: projects/walking-off-sunshine/secrets/VITE_GOOGLE_MAPS_API_KEY/versions/latest
      env: VITE_GOOGLE_MAPS_API_KEY
images:
  - ${_IMAGE}
